#ifndef SHARED_H
#define SHARED_H

#define PIPE_READ 0
#define PIPE_WRITE 1

#define MAX_PLAYER_NAME_CHARACTERS 20

// 1/10th second
#define TICK_TIME_MICROSECONDS 100000

#define CSERVER_WKP_NAME "CSERVER"

#endif